image: openjdk:8

pipelines:
  branches:
    master:
      - step:
          name: Build with gradle, Create & Push images to a Docker Registry
          caches:
            - gradle
            - docker
          script:
            - apt-get update
            # Add python pip and bash
            - apt-get -y install python3-minimal python3-pip
            # Install docker-compose via pip
            - pip3 install docker-compose
            - bash ./gradlew build -x test
            - docker-compose build
            - docker login $DOCKER_REPOSITORY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            # tag gateway
            - docker tag bomapoint/gateway $DOCKER_REPOSITORY/bomapoint/gateway
            # tag uaa
            - docker tag bomapoint/uaa $DOCKER_REPOSITORY/bomapoint/uaa
            # push gateway
            - docker push $DOCKER_REPOSITORY/bomapoint/gateway
            # push uaa
            - docker push $DOCKER_REPOSITORY/bomapoint/uaa
          services:
            - docker
