image: openjdk:8

pipelines:
  branches:
    develop:
      - step:
          name: Build with gradle, Create & Push images to a Docker Registry
          caches:
            - gradle
            - docker
          script:
            - apt-get update
            # Add python pip and bash
            - apt-get -y install python3-minimal python3-pip
            # Install docker-compose via pip
            - pip3 install docker-compose
            - bash ./gradlew build -x test
            - docker-compose build
            - docker login $DOCKER_REPOSITORY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker push $DOCKER_REPOSITORY bomapoint/gateway
            - docker push $DOCKER_REPOSITORY bomapoint/uaa
          services:
            - docker
