spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: boma-service
          uri: lb://boma-service
          predicates:
            - Path=/3rd-party/**
          filters:
            - RewritePath=/3rd-party/(?<segment>.*), /$\{segment}
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            - Path=/uaa-service/**
          filters:
            - RewritePath=/uaa-service/(?<segment>.*), /$\{segment}
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: bomapoint.com
      port: 8500
      discovery:
        hostname: infiware-gateway.herokuapp.com
        scheme: https
        port: 80
        health-check-url: https://infiware-gateway.herokuapp.com/actuator/health

server:
  port: 8762
