spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: boma-service
          uri: lb://boma-service
          predicates:
            - Path=/3rd-party/**
          filters:
            - RewritePath=/3rd-party/(?<segment>.*), /$\{segment}
            # Add following Filter Response header in order to remove duplicates CORS value for a Http Header
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            - Path=/uaa-service/**
          filters:
            - RewritePath=/uaa-service/(?<segment>.*), /$\{segment}
            # Add following Filter Response header in order to remove duplicates CORS value for a Http Header
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    ## consul discovery
    consul:
      host: bomapoint.com
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        heartbeat:
          enabled: true

server:
  port: 8762
